"""add display_id column to user table

Revision ID: c68407ddf9b5
Revises: e3dc9f41efe4
Create Date: 2024-06-20 12:27:16.913233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c68407ddf9b5'
down_revision = 'e3dc9f41efe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_id', sa.Integer(), server_default=sa.text('nextval(display_id_seq)'), nullable=True))
        batch_op.drop_index('username')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.drop_column('display_id')

    # ### end Alembic commands ###
