"""change primary key to id

Revision ID: e3dc9f41efe4
Revises: 
Create Date: 2024-06-20 12:01:16.692492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3dc9f41efe4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('riwayat')
    with op.batch_alter_table('pasien', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('nama',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('alamat',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('nohp',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_column('id_pasien')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.alter_column('nm_user',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('nohp',
               existing_type=mysql.VARCHAR(length=13),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['password'])
        batch_op.drop_column('id_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', mysql.INTEGER(display_width=15), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=False)
        batch_op.alter_column('nohp',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=13),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('nm_user',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('id')

    with op.batch_alter_table('pasien', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_pasien', mysql.INTEGER(display_width=35), autoincrement=True, nullable=False))
        batch_op.alter_column('nohp',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=False)
        batch_op.alter_column('alamat',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('nama',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('id')

    op.create_table('riwayat',
    sa.Column('no_riwayat', mysql.INTEGER(display_width=15), autoincrement=True, nullable=False),
    sa.Column('nama', mysql.VARCHAR(length=75), nullable=False),
    sa.Column('alamat', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('nohp', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('hasil', mysql.VARCHAR(length=15), nullable=False),
    sa.PrimaryKeyConstraint('no_riwayat'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
